# Generated by Django 5.0.2 on 2024-06-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0021_alter_area_nombre_area_alter_cargo_nombre_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre_departamento',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre_municipio',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='estado',
            field=models.TextField(choices=[('1', 'Aprobado'), ('2', 'Rechazado'), ('3', 'Pendiente')], default='Pendiente', max_length=10),
        ),
    ]
