# Generated by Django 5.0.2 on 2024-06-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0022_alter_departamento_nombre_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='dui',
            field=models.CharField(max_length=10),
        ),
    ]
